apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: testapp
        image: __IMAGE__
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: test-app
